version: '3.8'

services:
    at91_buildroot:
        container_name: at91_buildroot
        image: ${USER}/at91_buildroot
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"
        stdin_open: true  ## docker run -i
        tty: true         ## docker run -i
        #privileged: true
        environment:
         - USER
        env_file:
         - .env
        volumes:
         - ~/.gitconfig:/home/${USER}/.gitconfig:ro
         - ~/.ssh:/home/${USER}/.ssh:ro
         - ./buildroot:/home/${USER}/buildroot

