version: '3.8'

services:
    at91_buildroot:
        container_name: at91_buildroot
        image: ${USER}/at91_buildroot
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: ${USER}

        user: ${USER}
        stdin_open: true  ## docker run -i
        tty: true         ## docker run -i
        #privileged: true

        environment:
         - USER

        volumes:
         - ~/.gitconfig:/home/${USER}/.gitconfig
         - ~/.ssh:/home/${USER}/.ssh
         - ./buildroot:/home/${USER}/buildroot  ## folder does not need to be around

